[package]

name = "rustwarsaw"
version = "0.0.1"
authors = ["Zbigniew Siciarz <zbigniew@siciarz.net>"]

[dependencies]
rustc-serialize = "~0.3.14"
docopt = "~0.6.63"
iron = "~0.1.16"
mount = "~0.0.7"
staticfile = "~0.0.1"
